app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from .forms import Loginform, MyPasswordResetForm

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.home),
    path('registo/', views.CustomerRegistrationView.as_view(), name='registoutilizador'),
    path('profile/', views.profile, name='profile'),
    path('turmas/', views.TurmasView.as_view(), name='turmas'),
    path('turmasinscricoes/', views.TurmasInscricoesView.as_view(), name='turmasinscricoes'),

    path('acao/', views.AcoesView.as_view(), name='acao'),
    path('turmas/inscricao_detalhe/<int:pk>', views.InscricaoDetailView.as_view(), name='inscricao'),
    path('turmas/inscricao_detalhe/confirma/<int:pk>', views.add_insc, name='inscricaoconfirma'),
    path('listauserinscricao', views.lista_user_inscricao, name='inscricaouser'),
    path('listainscritos', views.InscricaoView.as_view(), name='listainscritos'),
    path('deleteuserinscricao/<int:inscricao_id>', views.delete_user_inscricao, name='deleteuserinscricao'),
    
    #Lista inscritos na turma
    path('turmas/turma_inscritos/<str:pk>/', views.turma_inscritos, name='turmainscritos'),
    path('turmas/gestao_inscricoes/', views.gestao_inscricoes, name='gestao_inscricoes'),

    path('turmas/turma_inscritos_pdf/<str:pk>/', views.turma_inscritos_pdf, name='turma_inscritos_pdf'),
    
    #User autentications
    path ('accounts/login/', auth_view.LoginView.as_view(template_name='login.html', authentication_form=Loginform), name='login'),
    path ('accounts/logout/', auth_view.LogoutView.as_view(), name='logout'),
    path ('accounts/password-reset/', auth_view.PasswordResetView.as_view(template_name='password_reset.html', form_class=MyPasswordResetForm), name='password_reset'),
    path ('criar_sessao/<int:turma>',views.criar_registo, name="criar_sessao"),
    path ('atualizar_sessao/<int:pk>',views.atualizar_registo, name="atualizar_sessao"),
    path ('apagar_registo/<int:pk>',views.apagar_registo, name="apagar_registo"),

    path ('calendas/',views.CalendasView.as_view(), name="calendas"),
    path ('calendas/<int:sort>',views.calendas, name="calendas"),

    path ('gerapdf',views.some_view, name="gerapdf"), 

   
]

cfaes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
]

app/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
from django.contrib.auth.models import User


ACAO_CHOICES=(
    ('CS', 'Curso'),
    ('OF', 'Oficina'),
    ('ACD', 'Ação de Curta Duração'),
    ('CE', 'Circulo de Estudos'))

DOC_CHOICES=(
    ('CC', 'Cartão de Cidadão'), 
    ('PP', 'Passaporte'),
    ('CR', 'Certificado de Residência'))

HAB_CHOICES=(
    ('DR', 'Doutoramento'), 
    ('MR', 'Mestrado'),
    ('LC', 'Licenciatura'))

GRUPO_CHOICES=(
    ('100', 'Educação Pré-Escolar'),
    ('110', '1º Ciclo'),
    ('120', 'Inglês'),
    ('550', 'Informática'), 
    
    )

ESCALAO_CHOICES=(
    ('1º', '1º Escalão'),
    ('2º', '2º Escalão'), 
    ('3º', '3º Escalão'),
    ('4º', '4º Escalão'),
    ('5º', '5º Escalão'),
    ('6º', '6º Escalão'),
    ('7º', '7º Escalão'),
    ('8º', '8º Escalão'),
    ('9º', '9º Escalão'),
    ('10º','10º Escalão'))

INDICE_CHOICES=(
    ('120º', '120'),
    ('130', '130'),
    ('240', '240'),
    ('500', '500'))

NIVEL_CHOICES=(
    ('PE', 'Pré- Escolar'), 
    ('1C', '1º ciclo'),
    ('2C', '2º ciclo'),
    ('3C', '3º ciclo'),
    ('SC', 'Secundário'),
    ('EE', 'Educação Especial'))

VINCULO_CHOICES=(
    ('QE', 'Quadro de Escola'),
    ('QZP', 'Quadro de zona'),
    ('CNT', 'Contratado'))

AGRUPAMENTO_CHOICES=(
    ('AEAS', 'Agrupamento de Escolas Abel Salazar'),
    ('AEPOL', 'Agrupamento de Escolas Prof. Óscar Lopes'),
    ('ESAG', 'Escola Secundária Auguto Gomes'),
    ('ZARCO', 'Escola Secundária João Gonçalves Zarco'),
    ('ESAG', 'Escola SEcundária Augusto Gomes'),
    ('ESBN', 'Escola secundária da Boa Nova'),
    ('AEP', 'Agrupamento de Escolas de Perafita'),
    ('AESH', 'Agrupamento de Escolas da Senhora da Hora'),
    ('AEFPO', 'Agrupamento de Escolas Fernando Pinto de Oliveira'),
    ('AEJDS', 'Agrupamento de Escolas José Domigues dos Santos'),
    ('AEIP', 'Agrupamento de Escolas de Irmãos Passos'),
    ('AESH', 'Agrupamento de Escolas da Senhora da Hora',))

REGIME_CHOICES=(
    ('O', 'Online'),
    ('P', 'Presencial'),
    ('H', 'Híbrido'))


class Acao(models.Model):
    codigo = models.CharField('Código da Ação', max_length=20)
    designacao = models.CharField('Designação da Ação', max_length=100)
    modalidade = models.CharField('Modalidade', max_length=3, choices=ACAO_CHOICES) 
    horas = models.IntegerField('Número de horas da ação', null=True)
    caducidade = models.DateField()
    registo = models.CharField('Número de Registo', max_length=40)
    acao_images = models.ImageField(upload_to='images')
    acao_doc = models.URLField('Descritivo da ação', default="http://cfaematosinhos.eu")

    def __str__(self):
        return self.designacao
    

class Docente(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo = models.CharField('Tipo de utilizador', max_length=20)
    nome = models.CharField('Nome', max_length=100)
    nascimento = models.DateField('data de nascimento')
    genero = models.CharField('Género', max_length=10, choices=[('M', 'Masculino'), ('F', 'Feminino')])
    nacionalidade = models.CharField('Nacionalidade', max_length=30, default='Portuguesa')
    identificacao = models.CharField('Documento de identificação', max_length=2,choices=DOC_CHOICES)
    numeroid = models.CharField('Número do Cartão', max_length=20)
    validadeid = models.DateField('Data de Validade')
    nif = models.CharField('NIF', max_length=10)
    niss = models.CharField('NISS', max_length=10)
    habilitacoes = models.CharField('Habilitações Literárias', max_length=25, choices=HAB_CHOICES)
    endereco = models.CharField('Endereço', max_length=60)
    codigopostal = models.CharField('Código Postal', max_length=8)
    localidade = models.CharField('Localidade', max_length=30)
    telemovel = models.CharField('Telemóvel', max_length=12)
    telefone = models.CharField('Telefone', max_length=12)
    datainiciofuncoes = models.DateField('Data início de funções', null=True)
    grupo = models.CharField('Grupo Disciplinar', max_length=3, null=True, choices=GRUPO_CHOICES)
    escalao = models.CharField('Escalão', max_length=3, null=True, choices=ESCALAO_CHOICES)
    proximaprogressao = models.DateField('Data da próxima progressão', null=True)
    indice = models.CharField('Indice', max_length=4, null=True, choices=INDICE_CHOICES)
    nivel = models.CharField('nivel de ensino',max_length=4, choices=NIVEL_CHOICES, default='SC')
    vinculo= models.CharField('nivel de ensino', max_length=4,choices=VINCULO_CHOICES, default='QE')
    agrupamento= models.CharField('nivel de ensino',max_length=5, choices=AGRUPAMENTO_CHOICES, default='ZARCO')
    formador = models.BooleanField("formador", default=False)
  

    def __str__(self):
        return self.nome


class Turma(models.Model):
    codigoacao = models.ForeignKey(Acao, blank=True, null=True, on_delete=models.CASCADE)
    turma = models.CharField('Turma', max_length=15, blank=True, null=True)
    datainicio = models.DateField()
    datafim = models.DateField()
    regime = models.CharField('Regime de frequência', max_length=4, null=True, choices=REGIME_CHOICES)
    publicoalvo = models.CharField("publico alvo", max_length=80, null=True, default="Professores do ensino básico e secundário")
    datainicioinsc = models.DateField('datainicioinscricao', default="2023-01-01")
    datalimiteinsc = models.DateField('datalimteinscricao', default="2023-01-01")
    fechada = models.BooleanField('Fechada', default=False)


    def __str__(self):
        return str(self.turma) 


class Sessoes(models.Model):
    codturma = models.ForeignKey(Turma, blank=True, null=True, on_delete=models.CASCADE)
    sessao = models.IntegerField()
    data = models.DateField()
    hora = models.TimeField()
    duracao = models.FloatField()
    localformacao = models.CharField('localformacao', max_length=50, blank=True, default="")
    sumario = models.TextField('localformacao', max_length=400, blank=True, default="")
    faltas = models.ManyToManyField(Docente)

    def __str__(self):
        return str(self.sessao)


class Inscritos(models.Model):
    idturma = models.ForeignKey(Turma, blank=True, null=True, on_delete=models.CASCADE)
    idutilizador = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    datahorainscricao = models.DateTimeField()
    confirmado = models.BooleanField('Confirma frequência', default=False)
    concluiu = models.BooleanField('concluiu a ação', default=False)
    classificacao = models.FloatField("Classificação", default=0)
    formador = models.BooleanField("formador", default=False)
    
    class Meta:
        unique_together = ('idturma', 'idutilizador')

    def __int__(self):
        return self.idturma
    

app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block main-content %}
    <h1>Bem vindo a este novo projeto que vai nascer aqui...</h1>
{% endblock main-content %}

app/templates/inscricaoconfirma.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block main-content %}
    <h1>Confirmada a inscrição</h1>
{% endblock main-content %}

app/templates/listaacoes.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block main-content %}

    <style>
        h1 {text-align: center}
        th,tr {font-size: 0.875em;text-align: left;}
        th {background-color: #4CAF50;color: white;}
        th, td {padding: 5px }
        table{margin: 0 auto}
         .linhas:hover {background-color: #f5f5f5}
    </style>
    
    <table>
        
        {% if acao_list %}
            <h1>Ações</h1>
            <thead>
            <tr>
                <th>imagem</th>
                <th>ID</th>
                <th>Designação</th>
                <th>Duração</th>
                <th>Modalidade</th>
                <th>Descritivo</th>

            </tr>
            </thead>
            
            <tbody>
        {% for item in acao_list %}
            <tr class="linhas">
                <td> <img src="/app/media/{{item.acao_images}}" width='70px'></td>
                <td>{{ item.id }}</td>
                <td>{{ item.designacao }}</td>
                <td>{{ item.horas }}</a></td>
                <td>{{ item.modalidade }}</td>
                <td><a href="{{ item.acao_doc }}" target="_blank">Descritvo</a></td>
            </tr>
                   
                    {% for trm in acao_list.turma_set.all %}
                    <tr class="linhas">
                        <td>
                        <strong> {{ trm.id }} </strong> - Turma  {{ trm.turma }} às {{ trm.inicio }}h
                        (duração:  {{ trm.duracao }} h) ||
                        </td>
                    </tr>
                    {% endfor %}
                
        {% endfor %}
        {% else %}
            <h1>Não existem Açoes</h1>
        {% endif %}
        </tbody>
    </table>
    
{% endblock main-content %}

app/templates/turmainscritos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Inscritos na turma{% endblock title %}
{% block main-content %}
    
    <style>
        h1 {text-align: center}
        th,tr {font-size: 0.875em;text-align: left;}
        th {background-color: #4CAF50;color: white;}
        th, td {padding: 5px }
        table{margin: 0 auto}
         .linhas:hover {background-color: #f5f5f5}
         a:link {
            text-decoration: none;
          }
    </style>
    
    <form action="{% url 'gestao_inscricoes'  %}" method='POST' enctype='multypart/form-data'>
        {% csrf_token %}
    <table> 
        
            <input id="id_turmat" type="text" name="turma_atual" value={{turma}} maxlength="100" readonly hidden>
            <h1>Turma {{turma}} - Formandos inscritos</h1>
            <thead>
            <tr>
                <th>Selecionar</th>
                <!--<th>Datahora inscrição</th>-->
                <th>Confirmado</th>
                <th>Username</th>
                <th>Nome</th>
                <th>Grupo</th>
                <th>Agrupamento</th> 
                <th>email</th>   
                <th>contacto</th>       
            </tr>
            </thead>
            <tbody> 
            <tr>
               
                {% for registo in inscritos %}
                    
                    <tr class="linhas">
                        <td><input name="checks[]" type="checkbox" value="{{registo.id }}" /></td>
                        <!--<td> {{ registo.datahorainscricao}} </td> -->
                        {% if registo.confirmado %} 
                        <td> 
                            <i class="fa fa-check fa-lg" aria-hidden="true" style="color:green"></i>
                        </td> 
                        {% else %} 
                        <td> 
                            <i class="fa fa-times fa-lg" aria-hidden="true" style="color:red"></i>
                        </td> 
                        {% endif %}  

                        <td> {{ registo.idutilizador}}  </td>
                        {% if registo.formador %}
                        <td> <strong>{{ registo.idutilizador.docente.nome}} (formador)</strong> </td>
                        {% else %}
                        <td> {{ registo.idutilizador.docente.nome}} </td>
                        {% endif %}
                        <td> {{ registo.idutilizador.docente.grupo}} </td> 
                        <td> {{ registo.idutilizador.docente.get_agrupamento_display}} </td>  
                        <td> {{ registo.idutilizador.email}} </td> 
                        <td> {{ registo.idutilizador.docente.telemovel}} </td>              
                    </tr>
                {% endfor %}
                
                <tr>
                    <td colspan='8'>
                        <hr>
                            <input type="submit" name="confirmar" value="Confirmar inscrições selecionadas" class="btn btn-sm btn-secondary"> 
                    </td> 
                </tr>
              
                <tr>
                    <td colspan='8'>
                        <hr>
                        
                            <select name="turma" id="turma" class="form-select form-select-sm">
                                {% for registo in listaturmas%}
                                    <option value={{registo.turma}}>{{registo.turma}} - {{registo.codigoacao}}</option>
                                {% endfor %}
                            </select>
                            <br>
                            <input type="submit"  name="mover" value="Mover os selecionados para a turma:" class="btn btn-sm btn-primary"> 
                    </td> 
                </tr>

                    <td colspan='8'>
                        <hr>
                            <select name="docente" id="docente" class="form-select form-select-sm">
                                {% for docente in listadocentes%}
                                    <option value={{docente.id}}>{{docente.nome}} - {{docente.grupo}}- {{docente.agrupamento}}</option>
                                {% endfor %}
                            </select>
                            <br>
                            <input type="submit" name="inscrever" value="Inscrever o formando selecionado" class="btn btn-sm btn-primary"> 
                    </td> 
                </tr>
                <tr>
                    <td colspan='8'>
                        <hr>
                            <select name="formador" id="formador" class="form-select form-select-sm">
                                {% for formador in listaformadores%}
                                    <option value={{formador.id}}>{{formador.nome}} - {{formador.grupo}}- {{formador.agrupamento}}</option>
                                {% endfor %}
                            </select>
                            <br>
                            <input type="submit" name="associar" value="Associar formador selecionado" class="btn btn-sm btn-primary"> 
                    </td> 
                </tr>

                <tr>
                    <td colspan='8'>
                        <hr>
                            <input type="submit" name="eliminar" value="eliminar selecionados" class="btn btn-sm btn-danger"> 
                    </td> 
                </tr>
            
            </tbody>
        </table>
        
    </form>
           
    
{% endblock main-content %}

app/templates/turmas.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Gestão da formação{% endblock title %}
{% block main-content %}

    <style>
        h1 {text-align: center}
        th,tr {font-size: 0.875em;text-align: left;}
        th {background-color: #4CAF50;color: white;}
        th, td {padding: 5px }
        table{margin: 0 auto}
         .linhas:hover {background-color: #f5f5f5}
         a:link {
            text-decoration: none;
          }
    </style>


    {% if turmas_list %}
        
        <table>
        <h1>Oferta formativa</h1>
        <tbody> 
        {% for item in turmas_list %}
         
        <tr>
        <td colspan="2"><h5 style="background-color:#CCC">{{ item.codigoacao }}</h5>
        </tr>
        <tr class="linhas">
        <td>      
            <i class="fa fa-users" aria-hidden="true"></i>
            Turma: {{ item.turma }} 
            &nbsp; &nbsp;<i class="fa fa-calendar" aria-hidden="true"></i>
            {{ item.datainicio }} a {{ item.datafim }}<br>
            
            <i class="fa fa-graduation-cap" aria-hidden="true"></i>
            Modalidade: {{ item.codigoacao.get_modalidade_display}} 
            &nbsp; &nbsp;<i class="fa fa-clock-o" aria-hidden="true"></i>
            Duração: {{ item.codigoacao.horas }}h 
            &nbsp; &nbsp;<i class="fa fa-map-marker" aria-hidden="true"></i>
            {{ item.get_regime_display }}<br>
            
            <i class="fa fa-user" aria-hidden="true"></i>  
            &nbsp;Formador(es):
            {% for registo in item.inscritos_set.all %}
                {% if registo.formador %}
                    {{ registo.idutilizador.docente.nome }}&nbsp;|      
                {% endif %}   
            {% endfor %}
            <br>

            <i class="fa fa-users" aria-hidden="true"></i>   
            Publico alvo: {{ item.publicoalvo }}

            <!--Sessões de formação-->
            <br>
            <div style="font-size: 0.875em">
                <hr>
            {% for sessao in item.sessoes_set.all|dictsort:"data" %}
            <i class="fa fa-calendar" aria-hidden="true"></i>
                    <strong>  Sessão {{ sessao.sessao }} </strong> - {{ sessao.data }} às {{ sessao.hora }}h
                    ({{ sessao.duracao }} h) <br>
            {% endfor %}
            </div>
        </td>
                
                <!--Estado da ação de formação-->

                {% now "Y-m-d" as todays_date %}
                
                {% if todays_date < item.datainicioinsc|date:"Y-m-d" %}
                    <td><a class="btn btn-warning btn-sm" href=""><i class="fa fa-spinner" aria-hidden="true"></i> Em preparação</a></td>
                {% else %}  
                    {% if todays_date <= item.datalimiteinsc|date:"Y-m-d" %}
                        {% if user.is_authenticated %}
                            {% if user.docente.username %}
                                <td><a class="btn btn-success btn-sm" href="inscricao_detalhe/{{item.id}}">Inscrever-me</a>
                                <br> Data limite:<br>  {{item.datalimiteinsc}}</td>
                            {% else %} 
                                <td><a class="btn btn-success btn-sm" href="/profile">Inscrever-me</a></td>
                            {% endif %}
                        {% else %}
                                <td><a class="btn btn-success btn-sm" href="/accounts/login">Inscrever-me</a></td>  
                        {% endif %}
                    {% else %}
                        {% if todays_date < item.datainicio|date:"Y-m-d" %}
                            <td><a class="btn btn-info btn-sm " href="#"><i class="fa fa-lock" aria-hidden="true"></i> Inscrições fechadas</a></td>
                        {% else %}
                            {% if todays_date <= item.datafim|date:"Y-m-d" %}
                                <td><a class="btn btn-primary btn-sm " href="#"><i class="fa fa-unlock" aria-hidden="true"></i> A decorrer</a></td>
                            {% else %}
                                {% if item.fechada  %}
                                    <td><a class="btn btn-secondary btn-sm" href="#"><i class="fa fa-lock" aria-hidden="true"> Fechada</a></td>
                                {% else %}
                                    <td><a class="btn btn-secondary btn-sm" href="#">Aguarda relatório</a></td>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}    
            </tr> 
                  
            


            <!--Formandos inscritos-->
             <tr> 
                <td colspan="2" 
                    class="d-inline-flex gap-1">
                    <button class="btn btn-light btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#{{item}}" aria-expanded="false" aria-controls="{{item}}">
                        Inscritos ({{item.inscritos_set.all.count}})
                    </button>
                </td>
            </tr>

            <tr>
                <td colspan="2">

            <div class="collapse" id="{{item}}">
                <p  style="background-color:#f2f2f2">
                    {% for registo in item.inscritos_set.all|dictsort:"idutilizador.docente.nome" %}
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <strong>{{ registo.idutilizador.docente.nome }} </strong>
                            ({{ registo.idutilizador.docente.grupo}}) 
                            &nbsp;
                            {{ registo.idutilizador.email}}
                            &nbsp;
                            {% if registo.formador  %}
                            (Formador)
                            {% else %}
                            {% if item.fechada %}
                                {% if registo.concluiu %}
                                <strong> (Classificação: {{registo.classificacao}})</strong>
                                {% else %}
                                    (Não concluiu)
                                {% endif %}
                            {% endif %}
                            {% endif %} 
                            <br>
                            {{ registo.idutilizador.docente.get_agrupamento_display}}
                            <br>
                      
                    {% endfor %}
                    </p>  
                    <a href="turma_inscritos/{{item.id}}">[Gerir inscrições]</a>  &nbsp; &nbsp;  
                    <a href="turma_inscritos_pdf/{{item.id}}">[Imprimir Pdf]</a>        
                </td>  
            </tr>
            </div>
            </div>  
   
        {% endfor %}
        
        {% else %}
            <h1>Não existem turmas</h1>
        {% endif %}
        </tbody>
    </table>

{% endblock main-content %}

app/templates/turmasinscricoes.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Gestão da formação{% endblock title %}
{% block main-content %}

    <style>
        h1 {text-align: center}
        th,tr {font-size: 0.875em;text-align: left;}
        th {background-color: #4CAF50;color: white;}
        th, td {padding: 5px }
        table{margin: 0 auto}
         .linhas:hover {background-color: #f5f5f5}
         a:link {
            text-decoration: none;
          }
    </style>


    {% if turmas_list %}
        <h1>Oferta formativa</h1>
        <table>
        <tbody> 
        {% for item in turmas_list %}

            {% now "Y-m-d" as todays_date %}
            {% if todays_date <= item.datalimiteinsc|date:"Y-m-d" %}
                {% if todays_date >= item.datainicioinsc|date:"Y-m-d" %}

                    <tr class="linhas">
                        <td> <img src="/static/app/{{item.codigoacao.acao_images}}" width='100px'></td>

                        <td><h5>{{ item.codigoacao }}</h5>
                        <i class="fa fa-users" aria-hidden="true"></i>
                        Turma: {{ item.turma }} 
                        &nbsp; &nbsp;<i class="fa fa-calendar" aria-hidden="true"></i>
                        {{ item.datainicio }} a {{ item.datafim }}<br>
                        <i class="fa fa-graduation-cap" aria-hidden="true"></i>
                        Modalidade: {{ item.codigoacao.get_modalidade_display}} 
                        &nbsp; &nbsp;<i class="fa fa-clock-o" aria-hidden="true"></i>
                        Duração: {{ item.codigoacao.horas }}h 
                        &nbsp; &nbsp;<i class="fa fa-map-marker" aria-hidden="true"></i>
                        {{ item.get_regime_display }}
                        <br>
                        <i class="fa fa-user" aria-hidden="true"></i>  
                        &nbsp;Formador(es):
                        {% for registo in item.inscritos_set.all %}
                            {% if registo.formador %}
                                {{ registo.idutilizador.docente.nome }}&nbsp;|      
                            {% endif %}  
                        
                        {% endfor %}
                        <br>

                        <i class="fa fa-users" aria-hidden="true"></i>   
                        Publico alvo: {{ item.publicoalvo }}

                        <hr>

                        {% for sessao in item.sessoes_set.all %}
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                                <strong>  Sessão {{ sessao.sessao }} </strong> - {{ sessao.data }} às {{ sessao.hora }}h
                                (duração:  {{ sessao.duracao }} h) <br>
                        {% endfor %}
                    
                        </td>          

                        {% if user.is_authenticated %}
                            {% if user.docente.username %}
                                <td><a class="btn btn-success btn-sm" href="inscricao_detalhe/{{item.id}}">Inscrever-me</a>
                                <br> Data limite:<br>  {{item.datalimiteinsc}}</td>
                            {% else %} 
                                <td><a class="btn btn-success btn-sm" href="/profile">Inscrever-me</a></td>
                            {% endif %}
                        {% else %}
                                <td><a class="btn btn-success btn-sm" href="/accounts/login">Inscrever-me</a></td>  
                        {% endif %}
                
                    </tr> 
                            
                    <tr> 
                        <td>&nbsp;</td>
                        <td colspan="3" 
                            class="d-inline-flex gap-1">
                            <button class="btn btn-light btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#{{item}}" aria-expanded="false" aria-controls="{{item}}">
                                Ver inscritos ({{item.inscritos_set.all.count}})
                            </button>
                        </td>
                    </tr>
                    {% endif %}  

            <tr>
                <td>&nbsp;</td>
                <td colspan="3">

            <div class="collapse" id="{{item}}">
                <p class="card card-body">
                    {% for registo in item.inscritos_set.all %}
                        
                            <span class="fa fa-user" aria-hidden="true">
                            {{ registo.idutilizador.docente.nome}}  
                            ({{ registo.idutilizador.docente.grupo}}) 
                            &nbsp;
                            {{ registo.idutilizador.email}}
                            &nbsp;
                            {{ registo.idutilizador.docente.get_agrupamento_display}}
                            &nbsp;
                            {% if registo.formador  %}
                                (FORMADOR)
                            {% else %}
                                {% if item.fechada %}
                                    {% if registo.concluiu %}
                                    <strong> (Classificação: {{registo.classificacao}})</strong>
                                    {% else %}
                                        (Não concluiu)
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                            <br>
                    {% endfor %}
                    
                    <a href="turma_inscritos/{{item.id}}">Ver detalhe</a>          
                </td>  
            </tr>
            </div>
            </div>  
        {% endif %}  
        {% endfor %}
        
        
    {% else %}
        <h1>Não existem turmas</h1>
    {% endif %}
        </tbody>
    </table>

{% endblock main-content %}